def eko(wordls):

    bin_dictionary = {
    # --- PAPIER: Niebieski pojemnik ---
    "GAZETA": "Niebieski pojemnik",
    "CZASOPISMO": "Niebieski pojemnik",
    "ULOTKA REKLAMOWA": "Niebieski pojemnik",
    "KSIĄŻKA W MIĘKKIEJ OPRAWIE": "Niebieski pojemnik",
    "ZESZYT": "Niebieski pojemnik",
    "KARTKA PAPIERU": "Niebieski pojemnik",
    "TORBA PAPIEROWA": "Niebieski pojemnik",
    "PUDEŁKO KARTONOWE": "Niebieski pojemnik",
    "TEKTURA FALISTA": "Niebieski pojemnik",
    "ROLKA PO PAPIERZE TOALETOWYM": "Niebieski pojemnik",
    "ROLKA PO RĘCZNIKU PAPIEROWYM": "Niebieski pojemnik",
    "KOPERTA (BEZ FOLII)": "Niebieski pojemnik",
    "PAPIER DO PAKOWANIA PREZENTÓW (NIE FOLIOWANY)": "Niebieski pojemnik",
    "BILET AUTOBUSOWY": "Niebieski pojemnik",
    "WYDRUK KOMPUTEROWY": "Niebieski pojemnik",
    "PUDEŁKO PO BUTACH": "Niebieski pojemnik",
    "KARTONOWY WYKŁADZINA NA JAJKA": "Niebieski pojemnik",

    # --- SZKŁO: Zielony pojemnik ---
    "BUTELKA PO PIWIE": "Zielony pojemnik",
    "BUTELKA PO WINIE": "Zielony pojemnik",
    "SŁOIK PO DŻEMIE": "Zielony pojemnik",
    "SŁOIK PO KONCENTRACIE POMIDOROWYM": "Zielony pojemnik",
    "BUTELKA PO SOKU (SZKLANA)": "Zielony pojemnik",
    "SŁOIK PO OGÓRKACH": "Zielony pojemnik",
    "OPAKOWANIE PO PERFUMACH (SZKLANE)": "Zielony pojemnik",
    "BUTELKA PO OLIWIE": "Zielony pojemnik",
    "PUSTY SŁOIK PO KAWIE ROZPUSZCZALNEJ": "Zielony pojemnik",
    "BUTELKA PO WODZIE MINERALNEJ (SZKLANA)": "Zielony pojemnik",

    # --- METALE I TWORZYWA SZTUCZNE: Żółty pojemnik ---
    "PLASTIKOWA BUTELKA PO WODZIE (PET)": "Żółty pojemnik",
    "PLASTIKOWA BUTELKA PO NAPOJU": "Żółty pojemnik",
    "KARTON PO MLEKU (TETRA PAK)": "Żółty pojemnik",
    "KARTON PO SOKU": "Żółty pojemnik",
    "PUSZKA PO NAPOJU (ALUMINIOWA)": "Żółty pojemnik",
    "PUSZKA PO KONSERWIE (STALOWA)": "Żółty pojemnik",
    "FOLIA ALUMINIOWA": "Żółty pojemnik",
    "PLASTIKOWY KUBECZEK PO JOGURCIE": "Żółty pojemnik",
    "OPAKOWANIE PO SERKU WIEJSKIM": "Żółty pojemnik",
    "PLASTIKOWA NAKRĘTKA OD BUTELKI": "Żółty pojemnik",
    "METALOWA ZAKRĘTKA OD SŁOIKA": "Żółty pojemnik",
    "OPAKOWANIE PO CHIPSACH": "Żółty pojemnik",
    "PLASTIKOWA TORBA NA ZAKUPY": "Żółty pojemnik",
    "FOLIA BĄBELKOWA": "Żółty pojemnik",
    "OPAKOWANIE PO CHEMII GOSPODARCZEJ (PUSTE)": "Żółty pojemnik",
    "BUTELKA PO SZAMPONIE": "Żółty pojemnik",
    "OPAKOWANIE PO MYDLE W PŁYNIE": "Żółty pojemnik",
    "DONICZKA PLASTIKOWA": "Żółty pojemnik",
    "PLASTIKOWE OPAKOWANIE PO OWOCACH": "Żółty pojemnik",
    "STYROPIAN OPAKOWANIOWY (MAŁY)": "Żółty pojemnik",
    "OPAKOWANIE PO MAŚLE/MARGARYNIE": "Żółty pojemnik",
    "KAPSEL OD PIWA": "Żółty pojemnik",
    "PUSTA TUBKA PO PAŚCIE DO ZĘBÓW": "Żółty pojemnik",
    "WIADRO PLASTIKOWE": "Żółty pojemnik",
    "ZABAWKA (BEZ BATERII, GŁÓWNIE PLASTIK)": "Żółty pojemnik",

    # --- ODPADY BIO: Brązowy pojemnik ---
    "OBIERKI Z ZIEMNIAKÓW": "Brązowy pojemnik",
    "RESZTKI WARZYW": "Brązowy pojemnik",
    "OGRYZEK JABŁKA": "Brązowy pojemnik",
    "SKÓRKA OD BANANA": "Brązowy pojemnik",
    "FUSY PO KAWIE": "Brązowy pojemnik",
    "TOREBKA PO HERBACIE EKSPRESOWEJ": "Brązowy pojemnik",
    "RESZTKI HERBATY LIŚCIASTEJ": "Brązowy pojemnik",
    "SKORUPKI JAJEK": "Brązowy pojemnik",
    "ZWIĘDŁE KWIATY": "Brązowy pojemnik",
    "SKOSZONA TRAWA": "Brązowy pojemnik",
    "LIŚCIE": "Brązowy pojemnik",
    "DROBNE GAŁĘZIE": "Brązowy pojemnik",
    "RESZTKI OWOCÓW": "Brązowy pojemnik",
    "PESTKI Z ARBUZA": "Brązowy pojemnik",
    "TROCINY (NIEIMPREGNOWANE)": "Brązowy pojemnik",
    "NIEZJEDZONY CHLEB": "Brązowy pojemnik",

    # --- ODPADY ZMIESZANE: Czarny pojemnik ---
    "RESZTKI MIĘSA": "Czarny pojemnik",
    "KOŚCI": "Czarny pojemnik",
    "ZUŻYTY RĘCZNIK PAPIEROWY": "Czarny pojemnik",
    "PARAGON FISKALNY": "Czarny pojemnik",
    "ZUŻYTA CHUSTECZKA HIGIENICZNA": "Czarny pojemnik",
    "WACIK KOSMETYCZNY": "Czarny pojemnik",
    "PATYCZEK DO USZU": "Czarny pojemnik",
    "ZUŻYTA PIELUCHA JEDNORAZOWA": "Czarny pojemnik",
    "PODPASKA/TAMPON": "Czarny pojemnik",
    "ROZBITY TALERZ CERAMICZNY": "Czarny pojemnik",
    "POTŁUCZONA SZKLANKA": "Czarny pojemnik",
    "STARE LUSTRO": "Czarny pojemnik",
    "ŻWIREK DLA KOTA": "Czarny pojemnik",
    "ODCHODY ZWIERZĘCE": "Czarny pojemnik",
    "WOREK Z ODKURZACZA": "Czarny pojemnik",
    "NIEDOPAŁEK PAPIEROSA": "Czarny pojemnik",
    "ZUŻYTA ŻARÓWKA (TRADYCYJNA)": "Czarny pojemnik",
    "SKÓRZANY PASEK": "Czarny pojemnik",
    "GĄBKA DO MYCIA NACZYŃ": "Czarny pojemnik",
    "ZUŻYTA SZCZOTECZKA DO ZĘBÓW": "Czarny pojemnik",
    "ZUŻYTY OLEJ PO SMAŻENIU (W ZAMKNIĘTYM POJEMNIKU)": "Czarny pojemnik",
    "POPIÓŁ Z KOMINKA": "Czarny pojemnik",
    "OPAKOWANIE PO LEKACH": "Czarny pojemnik",
    "ZDJĘCIA FOTOGRAFICZNE": "Czarny pojemnik",
    "UBRANIA NIENADAJĄCE SIĘ DO NOSZENIA": "Czarny pojemnik"
}

    if wordls in bin_dictionary:
        return bin_dictionary[wordls]
    else:
        return ("Nie ma takiego słowa!")